Areas/Admin/Controllers/CategoryController.cs
using Delivery_System;
using Delivery_System.DataAccess.Data;
using Delivery_System.DataAccess.Repository;
using Delivery_System.DataAccess.Repository.IRepository;
using Delivery_System.Models;
using Delivery_System_Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

[Area("Admin")]
[Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
public class CategoryController : Controller
{
  private readonly IUnitOfWork _unitOfWork;

  public CategoryController(IUnitOfWork unitOfWork)
  {
    _unitOfWork = unitOfWork;
  }
  public IActionResult Index()
  {
    List<Category> categories = _unitOfWork.Category.GetAll().ToList();
    return View(categories);
  }

  public IActionResult Create()
  {
    return View();
  }

  [HttpPost]
  [ValidateAntiForgeryToken]
  public IActionResult Create(Category category)
  {
    if (ModelState.IsValid)
    {
      _unitOfWork.Category.Add(category);
      _unitOfWork.Save();
      return RedirectToAction("Index");
    }
    return View(category);
  }

  public IActionResult Edit(int id)
  {
    var category = _unitOfWork.Category.Get(u => u.Id == id);
    if (category == null)
    {
      return NotFound();
    }
    return View(category);
  }

  [HttpPost]
  [ValidateAntiForgeryToken]
  public IActionResult Edit(int id, Category category)
  {
    if (id != category.Id)
    {
      return BadRequest();
    }

    if (ModelState.IsValid)
    {
      try
      {
        _unitOfWork.Category.Update(category);
        _unitOfWork.Save();
      }
      catch (DbUpdateConcurrencyException)
      {
        return NotFound();
      }
      return RedirectToAction("Index");
    }
    return View(category);
  }

  [HttpPost]
  [ValidateAntiForgeryToken]
  public IActionResult Delete(int id)
  {
    var category = _unitOfWork.Category.Get(u => u.Id == id);
    if (category == null)
    {
      return NotFound();
    }

    _unitOfWork.Category.Remove(category);
    _unitOfWork.Save();
    return RedirectToAction("Index");
  }
}

Areas/Admin/Controllers/CompanyController.cs
using Delivery_System.DataAccess.Repository.IRepository;
using Delivery_System.Models;
using Delivery_System.Models.ViewModels;
using Delivery_System_Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace Delivery_System.Areas.Admin.Controllers
{
  [Area("Admin")]
  [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
  public class CompanyController : Controller
  {
    private readonly IUnitOfWork _unitOfWork;
    public CompanyController(IUnitOfWork unitOfWork)
    {
      _unitOfWork = unitOfWork;
    }
    public IActionResult Index()
    {
      List<Company> companies = _unitOfWork.Company.GetAll().ToList();
      return View(companies);
    }
    [HttpGet]
    public IActionResult Upsert(int? id)
    {
      if (id.HasValue && id.Value != 0)
      {
        Company company = _unitOfWork.Company.Get(u => u.Id == id.Value);
        return View(company);
      }
      else
      {
        return View(new Company());
      }
      
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(Company company)
    {
      if (ModelState.IsValid)
      {
        if (company.Id == 0)
        {
          _unitOfWork.Company.Add(company);
        }
        else
        {
          _unitOfWork.Company.Update(company);
        }

        _unitOfWork.Save();
        return RedirectToAction("Index");
      }
      else
      {
        return View(company);
      }
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete(int id)
    {
      var company = _unitOfWork.Company.Get(u => u.Id == id);
      if (company == null)
      {
        return NotFound();
      }

      _unitOfWork.Company.Remove(company);
      _unitOfWork.Save();
      return RedirectToAction("Index");
    }

  }
}

Areas/Admin/Controllers/OrderController.cs
using Delivery_System.DataAccess.Repository.IRepository;
using Delivery_System.Models;
using Delivery_System_Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Delivery_System.Models.ViewModels;

namespace Delivery_System.Areas.Admin.Controllers
{
  [Area("Admin")]
  [Authorize]
  public class OrderController : Controller
  {
    private readonly IUnitOfWork _unitOfWork;
    [BindProperty]
    public OrderVM OrderVM { get; set; }

    public OrderController(IUnitOfWork unitOfWork)
    {
      _unitOfWork = unitOfWork;
    }

    public IActionResult Index()
    {
      List<OrderHeader> orderHeaders;

      if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee))
      {
        // Admin or Employee: Retrieve all orders
        orderHeaders = _unitOfWork.OrderHeader.GetAll(includeProperties: "ApplicationUser").ToList();
      }
      else
      {
        // Regular User: Retrieve only the user's orders
        var userId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value;
        orderHeaders = _unitOfWork.OrderHeader.GetAll(
            u => u.ApplicationUserId == userId,
            includeProperties: "ApplicationUser"
        ).ToList();
      }

      return View(orderHeaders);
    }

    public IActionResult Detail(int id)
    {
      OrderVM OrderVM = new()
      {
        OrderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == id, includeProperties: "ApplicationUser"),
        OrderDetail = _unitOfWork.OrderDetail.GetAll(u => u.OrderHeaderId == id, includeProperties: "Product")
      };

      return View(OrderVM);
    }

    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
    [HttpPost]
    public IActionResult UpdateOrderDetail()
    {
      var orderHeaderFromDb = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);

      orderHeaderFromDb.Name = OrderVM.OrderHeader.Name;
      orderHeaderFromDb.PhoneNumber = OrderVM.OrderHeader.PhoneNumber;
      orderHeaderFromDb.StreetAddress = OrderVM.OrderHeader.StreetAddress;
      orderHeaderFromDb.City = OrderVM.OrderHeader.City;
      orderHeaderFromDb.State = OrderVM.OrderHeader.State;
      orderHeaderFromDb.PostalCode = OrderVM.OrderHeader.PostalCode;

      if (!string.IsNullOrEmpty(OrderVM.OrderHeader.Carrier))
      {
        orderHeaderFromDb.Carrier = OrderVM.OrderHeader.Carrier;
      }
      if (!string.IsNullOrEmpty(OrderVM.OrderHeader.TrackingNumber))
      {
        orderHeaderFromDb.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;
      }

      _unitOfWork.OrderHeader.Update(orderHeaderFromDb);
      _unitOfWork.Save();

      return RedirectToAction("Detail", new { id = orderHeaderFromDb.Id });
    }

    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
    [HttpPost]
    public IActionResult StartProcessing(int orderId)
    {
      var orderHeaderFromDb = _unitOfWork.OrderHeader.Get(u => u.Id == orderId);
      if (orderHeaderFromDb == null)
      {
        return NotFound();
      }

      _unitOfWork.OrderHeader.UpdateStatus(orderId, SD.StatusInProcess);
      _unitOfWork.Save();

      return RedirectToAction("Detail", new { id = orderId });
    }


    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
    [HttpPost]
    public IActionResult ShipOrder(int orderId, string carrier, string trackingNumber)
    {
      var orderHeaderFromDb = _unitOfWork.OrderHeader.Get(u => u.Id == orderId);
      if (orderHeaderFromDb == null)
      {
        return NotFound();
      }

      orderHeaderFromDb.TrackingNumber = trackingNumber;
      orderHeaderFromDb.Carrier = carrier;
      orderHeaderFromDb.OrderStatus = SD.StatusShipped;
      orderHeaderFromDb.ShippingDate = DateTime.Now;

      if (orderHeaderFromDb.PaymentStatus == SD.PaymentStatusDelayedPayment)
      {
        orderHeaderFromDb.PaymentDueDate = DateTime.Now.AddDays(30);
      }

      _unitOfWork.OrderHeader.Update(orderHeaderFromDb);
      _unitOfWork.Save();

      return RedirectToAction("Detail", new { id = orderId });
    }


  }
}

Areas/Customer/Controllers/DashboardsController.cs
using System.Diagnostics;
using System.Security.Claims;
using Delivery_System.DataAccess.Repository.IRepository;
using Delivery_System.Models;
using Delivery_System.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;

namespace Delivery_System.Areas.Customer.Controllers;

[Area("Customer")]
public class DashboardsController : Controller
{
  private readonly IUnitOfWork _unitOfWork;
  private readonly IWebHostEnvironment _webHostEnvironment;

  public DashboardsController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
  {
    _unitOfWork = unitOfWork;
    _webHostEnvironment = webHostEnvironment;
  }

  public IActionResult Index()
  {
    IEnumerable<Product> ProductList = _unitOfWork.Product.GetAll(includeProperties: "Category");
    return View(ProductList);
  }

  [HttpGet]
  public IActionResult Detail(int id)
  {

    ShoppingCart cart = new()
    {
      Product = _unitOfWork.Product.Get(u => u.Id == id, includeProperties: "Category"),
      Count = 1,
      ProductId = id
    };
    return View(cart);
  }

  [HttpPost]
  [Authorize]
  public IActionResult Detail(ShoppingCart shoppingCart)
  {
    var claimIdentity = (ClaimsIdentity)User.Identity;
    var userId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
    shoppingCart.ApplicationUserId = userId;

    shoppingCart.Id = 0;

    ShoppingCart cartFromDb = _unitOfWork.ShoppingCart.Get(u => u.ApplicationUserId == userId && u.ProductId == shoppingCart.ProductId);

    if (cartFromDb != null)
    {
      cartFromDb.Count += shoppingCart.Count;
      _unitOfWork.ShoppingCart.Update(cartFromDb);
    }
    else
    {
      _unitOfWork.ShoppingCart.Add(shoppingCart);
    }

    _unitOfWork.Save();

    return RedirectToAction("Index");
  }
}

Views/Shared/Sections/Menu/_VerticalMenu.cshtml
@{
    TempData.Keep();
    string? currentPage = ViewContext.HttpContext.Request.Path;
}


<!-- Menu -->
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class='app-brand demo @((@ViewData["navbarFull"] != null && Convert.ToBoolean(@ViewData["navbarFull"])) ? "d-xl-none" : "")'>
        <a asp-controller="Dashboards" asp-action="Index" class="app-brand-link">
            <span class="app-brand-logo demo me-1"> @await Html.PartialAsync("../_Partials/_Macros")</span>
            <span class="app-brand-text demo menu-text fw-semibold ms-2">Dashboard</span>
        </a>
        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto">
            <i class="mdi menu-toggle-icon d-xl-block align-middle mdi-20px"></i>
        </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <ul class="menu-inner py-1">
        <!-- Dashboards -->
        <li class='menu-item@(currentPage.EndsWith("/") || currentPage.StartsWith("/Dashboards") ? " active open" : "")'>
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons mdi mdi-home-outline"></i>
                <div>Dashboards</div>
            </a>
            <ul class="menu-sub">
                <li class='menu-item@(currentPage == "/" ? " active" : "")'>
                    <a asp-area="Customer" asp-controller="Dashboards" asp-action="Index" class="menu-link">
                        <div>Analytics</div>
                    </a>
                </li>
            </ul>
        </li>

        @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee))
        {
            <!-- Category -->
            <li class='menu-item@(currentPage.StartsWith("/Admin/Category") ? " active open" : "")'>
                <a href="javascript:void(0);" class="menu-link menu-toggle">
                    <i class="menu-icon tf-icons mdi mdi-window-maximize"></i>
                    <div>Category</div>
                </a>
                <ul class="menu-sub">
                    <li class='menu-item@(currentPage.StartsWith("/Admin/Category") ? " active" : "")'>
                        <a asp-area="Admin" asp-controller="Category" asp-action="Index" class="menu-link">
                            <div>List</div>
                        </a>
                    </li>
                </ul>
            </li>

            <!-- Company -->
            <li class='menu-item@(currentPage.StartsWith("/Admin/Company") ? " active open" : "")'>
                <a href="javascript:void(0);" class="menu-link menu-toggle">
                    <i class="menu-icon tf-icons mdi mdi-window-maximize"></i>
                    <div>Company</div>
                </a>
                <ul class="menu-sub">
                    <li class='menu-item@(currentPage.StartsWith("/Admin/Company") ? " active" : "")'>
                        <a asp-area="Admin" asp-controller="Company" asp-action="Index" class="menu-link">
                            <div>List</div>
                        </a>
                    </li>
                </ul>
            </li>

            <!-- Product -->
            <li class='menu-item@(currentPage.StartsWith("/Admin/Product") ? " active open" : "")'>
                <a href="javascript:void(0);" class="menu-link menu-toggle">
                    <i class="menu-icon tf-icons mdi mdi-window-maximize"></i>
                    <div>Product</div>
                </a>
                <ul class="menu-sub">
                    <li class='menu-item@(currentPage.StartsWith("/Admin/Product") ? " active" : "")'>
                        <a asp-area="Admin" asp-controller="Product" asp-action="Index" class="menu-link">
                            <div>List</div>
                        </a>
                    </li>
                </ul>
            </li>
        }

        <!-- Order -->
        <li class='menu-item@(currentPage.StartsWith("/Admin/Order") ? " active open" : "")'>
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons mdi mdi-window-maximize"></i>
                <div>Order</div>
            </a>
            <ul class="menu-sub">
                <li class='menu-item@(currentPage.StartsWith("/Admin/Order") ? " active" : "")'>
                    <a asp-area="Admin" asp-controller="Order" asp-action="Index" class="menu-link">
                        <div>Order Lists</div>
                    </a>
                </li>
            </ul>
        </li>
        

        <li class="menu-header fw-medium mt-4">
            <span class="menu-header-text">Apps &amp; Pages</span>
        </li>

        @* <!-- Layouts -->
        <li class='menu-item@(currentPage.StartsWith("/Category") ? " active open" : "")'>
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons mdi mdi-window-maximize"></i>
                <div>Category</div>
            </a>
            <ul class="menu-sub">
                <li class='menu-item@(currentPage.StartsWith("/Category") ? " active" : "")'>
                    <a asp-controller="Category" asp-action="Index" class="menu-link">
                        <div>List</div>
                    </a>
                </li>
            </ul>
        </li> *@

    </ul>
</aside>
<!-- / Menu -->